application: shimmyapp
version: 1
runtime: python
api_version: 1

# In production, uncomment line below.
# default_expiration: "30d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$

builtins:
- appstats: on
- remote_api: on
- datastore_admin: on

inbound_services:
- warmup

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /tasks/.+
  script: main.py
  login: admin

- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /images/(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))

- url: /swf/(.*\.swf)
  static_files: static/swf/\1
  upload: static/swf/(.*\.swf)

- url: /fonts/(.*\.css)
  mime_type: text/css
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.css)

- url: /fonts/(.*\.(woff|svg|eot))
  mime_type: application/octet-stream
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.(woff|svg|eot))

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /i/.*
  script: image.py

- url: /.*
  script: main.py
